version: 0.0
os: linux
files:
  - source: /
    destination: /traclytics_master
hooks:
  BeforeInstall:
    - location: scripts/install_pydependencies
      timeout: 300
      runas: root
    - location: scripts/start_pyserver
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_pyserver
      timeout: 300
      runas: root

