#!/bin/bash
COMP_FILE=/lib/systemd/system/master-aws-computation.service
SCHED_FILE=/lib/systemd/system/monitoring_scheduler.service
if [[ -f "$COMP_FILE" ]]; then
	sudo systemctl stop master-aws-computation.service
fi
if [[ -f "$SCHED_FILE" ]]; then
	sudo systemctl stop monitoring_scheduler.service
fi
